 ALTER TABLE user_profile
  ADD COLUMN kr_first_name VARCHAR(10) DEFAULT NULL,
  ADD COLUMN kr_last_name VARCHAR(10) DEFAULT NULL,
  ADD COLUMN birth DATE DEFAULT NULL,
  ADD COLUMN email VARCHAR(320) DEFAULT NULL,
  ADD COLUMN phone_number VARCHAR(20) NOT NULL DEFAULT '',
  ADD COLUMN passport_expiry_date DATE DEFAULT NULL,
  ADD COLUMN passport_issue_country VARCHAR(100) DEFAULT NULL;

 ALTER TABLE airport
     ADD COLUMN tag VARCHAR(50) NULL COMMENT '태그';