RENAME TABLE ADMIN TO admin;
RENAME TABLE ADMIN_ACTION_LOG TO admin_action_log;
RENAME TABLE ADMIN_NOTIFICATION TO admin_notification;
RENAME TABLE REFUND_POLICY TO refund_policy;
RENAME TABLE REFUND TO refund;
RENAME TABLE STATISTICS TO statistics;
RENAME TABLE EMAIL_LOG TO email_log;
RENAME TABLE BULK_UPLOAD_JOB TO bulk_upload_job;